[package]
name = "simple-towers"
version = "0.1.0"
authors = ["Nikola Stoyanov <ns.barzakov@gmail.com>"]
edition = "2018"

[dependencies]
# amethyst = { version = "0.10.0", features = ["nightly"] }
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["nightly"] }
derive_deref = "1.0.1"
multiarray = "0.1.3"
rand = "0.5.5"
serde = "1.0.80"
serde_derive = "1.0.80"

# TODO: move to dev-dependencies when docs for them can be built
amethyst_test = { git = "https://github.com/amethyst/amethyst.git", features = ["nightly"] }

[dev-dependencies]
