[package]
name = "simple-towers"
version = "0.1.0"
authors = ["Nikola Stoyanov <ns.barzakov@gmail.com>"]
edition = "2018"

[dependencies]
# amethyst = { version = "0.9.0", features = ["nightly"] }
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["nightly"] }
rand = "0.5.5"
serde = "1.0.80"
serde_derive = "1.0.80"
